FROM eclipse-mosquitto:2.0

# Enable anonymous access (vulnerable!)
RUN sed -i 's/#allow_anonymous false/allow_anonymous true/' /mosquitto/config/mosquitto.conf

EXPOSE 1883/tcp
CMD ["mosquitto","-c","/mosquitto/config/mosquitto.conf"]
