FROM ubuntu:22.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y bind9
COPY named.conf /etc/bind/named.conf
COPY db.test.local /etc/bind/db.test.local
EXPOSE 53/udp 53/tcp
CMD ["named", "-g", "-c", "/etc/bind/named.conf"]
